version: '3'

services:
  postgres:
    container_name: 'trpc-next-postgres'
    restart: unless-stopped
    build: integrations/postgres
    ports:
      # NOTE: To avoid overlapping with any Postgres database run on the host machine,
      # we bind Postgres to port "15432" instead.
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  pgdata: {}
